In [1]:
# import lib 
import pandas as pd

In [2]:
# 1.1 read data 
filename = 'iris.data'
df = pd.read_csv(filename)
df.head(5)

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [3]:
print(df.shape)

(149, 5)


In [4]:
names = list(df.columns)
print(names)
print(df[names[4]].unique())
df[names[4]].value_counts()

['5.1', '3.5', '1.4', '0.2', 'Iris-setosa']
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


Iris-versicolor    50
Iris-virginica     50
Iris-setosa        49
Name: Iris-setosa, dtype: int64

In [5]:
# convert to numpy
data = df.values
print(data.shape)
X = data[:,:-1]
y = data[:,-1]
print(X.shape)
print(y.shape)

(149, 5)
(149, 4)
(149,)


In [6]:
# split into train and test data sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42,
                                                    test_size=0.25)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(111, 4)
(111,)
(38, 4)
(38,)


In [7]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(X_train,y_train)
y_pred = LR.predict(X_test)

In [8]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[15  0  0]
 [ 0  8  3]
 [ 0  1 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       0.89      0.73      0.80        11
 Iris-virginica       0.79      0.92      0.85        12

       accuracy                           0.89        38
      macro avg       0.89      0.88      0.88        38
   weighted avg       0.90      0.89      0.89        38



In [9]:
LR.predict_proba(X_test[:2])

array([[9.16371957e-03, 9.18022917e-01, 7.28133638e-02],
       [9.77841062e-01, 2.21588587e-02, 7.93794182e-08]])