In [1]:
from tensorflow.keras import layers
from tensorflow.keras import models
import numpy as np 

In [2]:
import pandas as pd
dataframe = pd.read_csv("iris.data")
data = np.array(dataframe.values)
print(data.shape)

(149, 5)


In [3]:
X = data[:,:-1]
X = np.asarray(X.astype(np.float32))
y = data[:,-1]
print(X.shape)
print(y.shape)

(149, 4)
(149,)


In [4]:
from collections import Counter
counter = Counter()
counter.update(y)
print(counter)

Counter({'Iris-versicolor': 50, 'Iris-virginica': 50, 'Iris-setosa': 49})


In [5]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]


In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print('Train:')
print(X_train.shape)
print(y_train.shape)
print('Test:')
print(X_test.shape)
print(y_test.shape)

Train:
(104, 4)
(104,)
Test:
(45, 4)
(45,)


In [7]:
print(X_train[:2])

[[5.8 2.7 3.9 1.2]
 [6.3 2.8 5.1 1.5]]


In [8]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train)
print(y_train[:2])

[[0. 1. 0.]
 [0. 0. 1.]]


In [9]:
model = models.Sequential()
model.add(layers.Dense(16, activation='tanh'))
model.add(layers.Dense(32, activation='tanh'))
model.add(layers.Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', 
              metrics=['accuracy'])

In [10]:
model.fit(X_train,y_train,epochs=50, batch_size=10, verbose=2)

Epoch 1/50
11/11 - 1s - loss: 1.3489 - accuracy: 0.3558 - 991ms/epoch - 90ms/step
Epoch 2/50
11/11 - 0s - loss: 1.1677 - accuracy: 0.4423 - 27ms/epoch - 2ms/step
Epoch 3/50
11/11 - 0s - loss: 1.0683 - accuracy: 0.3558 - 27ms/epoch - 2ms/step
Epoch 4/50
11/11 - 0s - loss: 0.9522 - accuracy: 0.4712 - 26ms/epoch - 2ms/step
Epoch 5/50
11/11 - 0s - loss: 0.8587 - accuracy: 0.6731 - 25ms/epoch - 2ms/step
Epoch 6/50
11/11 - 0s - loss: 0.7748 - accuracy: 0.8750 - 24ms/epoch - 2ms/step
Epoch 7/50
11/11 - 0s - loss: 0.6979 - accuracy: 0.8846 - 27ms/epoch - 2ms/step
Epoch 8/50
11/11 - 0s - loss: 0.6382 - accuracy: 0.9615 - 31ms/epoch - 3ms/step
Epoch 9/50
11/11 - 0s - loss: 0.5798 - accuracy: 0.8846 - 27ms/epoch - 2ms/step
Epoch 10/50
11/11 - 0s - loss: 0.5337 - accuracy: 0.9231 - 24ms/epoch - 2ms/step
Epoch 11/50
11/11 - 0s - loss: 0.4903 - accuracy: 0.9712 - 28ms/epoch - 3ms/step
Epoch 12/50
11/11 - 0s - loss: 0.4570 - accuracy: 0.9808 - 20ms/epoch - 2ms/step
Epoch 13/50
11/11 - 0s - loss: 0.42

In [11]:
y_pred = model.predict(X_test)
print(y_pred[:2])

[[1.0471487e-02 9.8305398e-01 6.4745299e-03]
 [9.8874474e-01 1.1244364e-02 1.0979013e-05]]


In [12]:
y_pred = y_pred.argmax(axis=1)
print(y_pred)
print(y_test)

[1 0 2 1 1 0 1 2 1 2 2 0 0 0 0 1 2 2 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [13]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.85      0.92        13
           2       0.87      1.00      0.93        13

    accuracy                           0.96        45
   macro avg       0.96      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45

